# ビルドステージ: Go の公式イメージを使用
FROM golang:1.23-alpine
# curl をインストール
RUN apk update && apk add --no-cache curl

# モジュールファイルとソースコードのコピー
WORKDIR /app
COPY ./ .

RUN go mod tidy

# ポート8080を公開
EXPOSE 8080

# アプリケーションの起動
CMD ["tail", "-f", "/dev/null"]
